# Authorization Service specific configuration
server:
  port: 8083

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: ${DATABASE_USERNAME:auth_user}
    password: ${DATABASE_PASSWORD:auth_password}
    hikari:
      maximum-pool-size: 15
      minimum-idle: 3
      
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1 hour
      cache-null-values: false

# Authorization configuration
authorization:
  cache:
    permissions-ttl: ${PERMISSIONS_CACHE_TTL:1800000} # 30 minutes
    roles-ttl: ${ROLES_CACHE_TTL:3600000} # 1 hour
    user-roles-ttl: ${USER_ROLES_CACHE_TTL:1800000} # 30 minutes
    
  permissions:
    hierarchy:
      enabled: true
      admin-includes-all: true
      
  roles:
    default: USER
    system-roles:
      - SYSTEM
      - SERVICE
      - ADMIN
      - SUPER_ADMIN
      
# Role hierarchy configuration  
role-hierarchy:
  SUPER_ADMIN: ADMIN
  ADMIN: USER
  USER: GUEST

# Default permissions
default-permissions:
  GUEST:
    - "public:read"
  USER:
    - "user:read-self"
    - "user:update-self"
  ADMIN:
    - "user:*"
    - "role:*"
    - "permission:read"
  SUPER_ADMIN:
    - "*:*"
    
# Permission evaluation
permission-evaluation:
  strict-mode: ${STRICT_PERMISSION_MODE:true}
  allow-anonymous: ${ALLOW_ANONYMOUS:false}
  cache-decisions: ${CACHE_DECISIONS:true}
  decision-cache-ttl: ${DECISION_CACHE_TTL:300000} # 5 minutes

logging:
  level:
    com.company.auth.authorization: DEBUG
    org.springframework.security: INFO