spring:
  application:
    name: auth-service
  
  profiles:
    active: development
  main:
    allow-circular-references: true
  
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: auth_user
    password: auth_password
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
    
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        
  mail:
    host: localhost
    port: 1025
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 8081
  servlet:
    context-path: /
  forward-headers-strategy: native

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    com.company.auth: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId},%X{spanId}] %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{traceId},%X{spanId}] %logger{36} - %msg%n"

app:
  jwt:
    secret: ${JWT_SECRET:mySecretKeyThatIsAtLeast256BitsLongForHS256AlgorithmToWorkProperly}
    access-token-expiration-ms: ${JWT_ACCESS_EXPIRATION:900000}  # 15 minutes
    refresh-token-expiration-ms: ${JWT_REFRESH_EXPIRATION:86400000}  # 24 hours
    issuer: auth-service
    
  session:
    max-concurrent-sessions: 5
    expiration-hours: 24
    
  security:
    max-login-attempts: 5
    account-lockout-duration-minutes: 30
    password-reset-expiration-minutes: 60
    
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}
    allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

---
spring:
  config:
    activate:
      on-profile: development
      
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db_dev
    username: auth_user
    password: auth_password
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      
logging:
  level:
    com.company.auth: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

---
spring:
  config:
    activate:
      on-profile: production
      
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://db:5432/auth_db}
    username: ${DATABASE_USERNAME:auth_user}
    password: ${DATABASE_PASSWORD}
    
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    com.company.auth: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

---
spring:
  config:
    activate:
      on-profile: test
  main:
    allow-circular-references: true
      
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    
  flyway:
    enabled: false
    
  redis:
    host: localhost
    port: 6370  # Different port for tests

app:
  jwt:
    secret: testSecretKeyThatIsAtLeast256BitsLongForHS256AlgorithmToWorkProperlyInTests
    access-token-expiration-ms: 300000  # 5 minutes for tests
    refresh-token-expiration-ms: 600000  # 10 minutes for tests
