# =============================================================================
# Prometheus Configuration for IvyArc Spring Cloud Microservices
# =============================================================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'ivyarc-local'
    environment: 'development'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules.yml"

# Scrape configuration
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot Actuator endpoints
  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['eureka-server:8761']
        labels:
          service: 'eureka-server'
          type: 'infrastructure'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'eureka-server'

  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['config-server:8888']
        labels:
          service: 'config-server'
          type: 'infrastructure'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'config-server'

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['api-gateway:8080']
        labels:
          service: 'api-gateway'
          type: 'infrastructure'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'api-gateway'

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['auth-service:8081']
        labels:
          service: 'auth-service'
          type: 'core-service'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'auth-service'

  - job_name: 'authorization-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['authorization-service:8082']
        labels:
          service: 'authorization-service'
          type: 'core-service'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'authorization-service'

  - job_name: 'user-management-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['user-management-service:8083']
        labels:
          service: 'user-management-service'
          type: 'core-service'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'user-management-service'

  - job_name: 'audit-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['audit-service:8084']
        labels:
          service: 'audit-service'
          type: 'core-service'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'audit-service'

  # Infrastructure monitoring
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgresql'
          type: 'database'
    scrape_interval: 30s

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
          type: 'cache'
    scrape_interval: 30s

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
        labels:
          service: 'rabbitmq'
          type: 'message-broker'
    scrape_interval: 30s

  # Node exporter for system metrics (if running)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'
          type: 'system'
    scrape_interval: 30s

  # Service discovery via Eureka (alternative approach)
  - job_name: 'eureka-sd'
    eureka_sd_configs:
      - server: http://eureka-server:8761/eureka
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        target_label: job
      - source_labels: [__meta_eureka_app_instance_metadata_management_port]
        target_label: __address__
        replacement: ${__meta_eureka_app_instance_hostname}:${1}
      - target_label: __metrics_path__
        replacement: /actuator/prometheus
      - source_labels: [__meta_eureka_app_name]
        target_label: service
      - source_labels: [__meta_eureka_app_instance_id]
        target_label: instance